// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPQHWhDhqXWjVarAuIH2Sb7MMOOqLXhmI',
    appId: '1:548165128046:web:f433c35935d3df874dbb7f',
    messagingSenderId: '548165128046',
    projectId: 'flowboost-91bd0',
    authDomain: 'flowboost-91bd0.firebaseapp.com',
    storageBucket: 'flowboost-91bd0.firebasestorage.app',
    measurementId: 'G-JF0761HK3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZe35crb2e-39j5WGCWYD8CbXK4Rrftlw',
    appId: '1:548165128046:android:42091281d006bfd54dbb7f',
    messagingSenderId: '548165128046',
    projectId: 'flowboost-91bd0',
    storageBucket: 'flowboost-91bd0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7ljM69b-PYwP5AjwDKEU7a2BfSOnHUk4',
    appId: '1:548165128046:ios:dc9b236e1ee677384dbb7f',
    messagingSenderId: '548165128046',
    projectId: 'flowboost-91bd0',
    storageBucket: 'flowboost-91bd0.firebasestorage.app',
    iosBundleId: 'com.example.flowboost',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7ljM69b-PYwP5AjwDKEU7a2BfSOnHUk4',
    appId: '1:548165128046:ios:dc9b236e1ee677384dbb7f',
    messagingSenderId: '548165128046',
    projectId: 'flowboost-91bd0',
    storageBucket: 'flowboost-91bd0.firebasestorage.app',
    iosBundleId: 'com.example.flowboost',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPQHWhDhqXWjVarAuIH2Sb7MMOOqLXhmI',
    appId: '1:548165128046:web:1639119fcf582e1e4dbb7f',
    messagingSenderId: '548165128046',
    projectId: 'flowboost-91bd0',
    authDomain: 'flowboost-91bd0.firebaseapp.com',
    storageBucket: 'flowboost-91bd0.firebasestorage.app',
    measurementId: 'G-0ZTEZPN0BQ',
  );

}